////////////////////////// Data States \\\\\\\\\\\\\\\\\\\\\\\\\\
// global params
var currentTrack = 0;
var currentStep = 0;
var currentPage = 0;
var length = "1m";
var running = false;
var changes = false;
var loggedIn = false;
var openModal = null;

// massive JSON objects to contain all information
// currentData is the live object
// projectData is the master object that interacts with the api
// initData is an init object with default parameters
var initData = {
    id: null,
    name: "",
    bpm: 120,
    swing: 0,
    masterVolume: -6,
    length: "1m",
    tracks: [
        {
            id: 0,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 1,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 2,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 3,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 4,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 5,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 6,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 7,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 8,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 9,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 99,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
    ],
    master: {
        dirt: 20,
        dirtMix: 0.2,
        space: 2.0,
        predelay: 0.01,
        revWidth: 0.3,
        revLimit: -3,
        eqLow: 0,
        eqMid: 0,
        eqHigh: 0,
        compThresh: -24,
        compRatio: 1,
        compAttack: 0.05,
        compRelease: 0.25,
        compKnee: 30,
        satDrive: 0,
        satTone: 20000,
        satMix: 0,
        limitThresh: -3,
    },
};

var currentData = {
    id: 0,
    name: "",
    bpm: 120,
    swing: 0,
    masterVolume: -6,
    length: "1m",
    tracks: [
        {
            id: 0,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 1,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 2,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 3,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 4,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 5,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 6,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 7,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 8,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 9,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 99,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
    ],
    master: {
        dirt: 20,
        dirtMix: 0.2,
        space: 2.0,
        predelay: 0.01,
        revWidth: 0.3,
        revLimit: -3,
        eqLow: 0,
        eqMid: 0,
        eqHigh: 0,
        compThresh: -24,
        compRatio: 1,
        compAttack: 0.05,
        compRelease: 0.25,
        compKnee: 30,
        satDrive: 0,
        satTone: 20000,
        satMix: 0,
        limitThresh: -3,
    },
};

var projectData = {
    id: 0,
    name: "",
    bpm: 120,
    swing: 0,
    masterVolume: -6,
    length: "1m",
    tracks: [
        {
            id: 0,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 1,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 2,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 3,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 4,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 5,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 6,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 7,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 8,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 9,
            samplePath: "",
            sampleName: "New Sequence",
            volume: -12,
            muted: false,
            pitch: 0,
            pan: 0,
            start: 0,
            attack: 0,
            decay: 2,
            sustain: 1,
            release: 0,
            lpWidth: 5000,
            lpq: 0,
            hpWidth: 1,
            hpq: 0,
            distortion: 0,
            bitcrusher: 0,
            reverb: 0,
            chorusRate: 0,
            chorusDepth: 0,
            chorusMix: 0,
            tremRate: 0,
            tremDepth: 0,
            tremMix: 0,
            delTime: 0,
            delFback: 0,
            delMix: 0,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
        {
            id: 99,
            steps: [
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0,
            ],
        },
    ],
    master: {
        dirt: 20,
        dirtMix: 0.2,
        space: 2.0,
        predelay: 0.01,
        revWidth: 0.3,
        revLimit: -3,
        eqLow: 0,
        eqMid: 0,
        eqHigh: 0,
        compThresh: -24,
        compRatio: 1,
        compAttack: 0.05,
        compRelease: 0.25,
        compKnee: 30,
        satDrive: 0,
        satTone: 20000,
        satMix: 0,
        limitThresh: -3,
    },
};
